- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory


- name: downlaod backned code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component}}-v2.zip
    dest: /tmp/backend.zip

- name: downlaod extract code
  ansible.builtin.unarchive:
    src: /tmp/backend.zip # By default 
    dest: "{{ app_location }}"
    remote_src: yes    
